spring.application.name=Vektor-Invest-Backend-Spring

#MySQL
spring.datasource.url=${URL_DATABASE_MYSQL}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${PASSWORD_DATABASE}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# JWT
session.secret=${SECRET_OAUTH}
time.rememberMe=${TIME_REMEMBER_ME}

# Variavel ambiente url python
python.api.url=${PYTHON_VEKTOR_API}


# Configurações para autenticação via Google
spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID_OAUTH}
spring.security.oauth2.client.registration.google.client-secret=${SECRET_OAUTH}
spring.security.oauth2.client.registration.google.scope=email, profile