spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vektor?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: marcossouza144
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    secret: ${SESSION_SECRET}