spring:
  application:
    name: Vektor-Invest-Backend-Spring

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID_OAUTH}
            client-secret: ${SECRET_OAUTH}